[package]
name = "words"
version = "0.1.0"
authors = ["Andrew Smith <andrewchristophersmith@gmail.com>"]

[dependencies]
astar = { path = "/Users/acsmith/workspaces/rust/astar" }
edit-distance = "1.0"
simple_parallel = "0.3"
